# Generated by Django 4.2.13 on 2024-05-28 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0002_schedule_gpa'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='semester',
            field=models.IntegerField(default=1),
        ),
    ]
