# Generated by Django 4.2.13 on 2024-06-07 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0003_schedule_semester'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='pennkey',
            field=models.CharField(max_length=100),
        ),
    ]
